/**
 * Simple test file to verify the frontmatter system works correctly
 * Run this with: bun run dev and check console output
 */

import {
  parseFrontmatter,
  createFrontmatterBlock,
  validateFrontmatter,
  type FrontmatterData,
  getAllBlogMeta,
  getBlogBySlug,
  getFeaturedBlogs,
  getBlogStats,
} from "./blogProcessor";

/**
 * Test frontmatter parsing
 */
export const testFrontmatterParsing = () => {
  console.log("=== Testing Frontmatter Parsing ===");

  // Test with frontmatter
  const markdownWithFrontmatter = `---
title: "Test Blog Post"
date: "2024-12-19"
tags: ["test", "demo"]
featured: true
draft: false
---

# Test Content
This is a test blog post.`;

  const result1 = parseFrontmatter(markdownWithFrontmatter);
  console.log("✅ Parsed frontmatter:", result1.frontmatter);
  console.log("✅ Has frontmatter:", result1.hasFrontmatter);
  console.log(
    "✅ Content preview:",
    result1.content.substring(0, 50) + "...\n"
  );

  // Test without frontmatter (legacy format)
  const markdownWithoutFrontmatter = `# Legacy Blog Post

*Date: 2024-06-01*

This is a legacy blog post without frontmatter.`;

  const result2 = parseFrontmatter(markdownWithoutFrontmatter);
  console.log("✅ Legacy format - Has frontmatter:", result2.hasFrontmatter);
  console.log("✅ Legacy format - Default frontmatter:", result2.frontmatter);
  console.log(
    "✅ Legacy format - Full content preserved:",
    result2.content === markdownWithoutFrontmatter,
    "\n"
  );
};

/**
 * Test frontmatter creation and validation
 */
export const testFrontmatterCreation = () => {
  console.log("=== Testing Frontmatter Creation ===");

  const frontmatterData: FrontmatterData = {
    title: "Generated Blog Post",
    date: "2024-12-19",
    author: "Test Author",
    tags: ["generated", "test"],
    category: "Testing",
    description: "A test blog post generated by code",
    featured: false,
    draft: true,
    location: {
      name: "Test Location",
      coordinates: {
        lat: -33.8688,
        lng: 151.2093,
      },
    },
  };

  const frontmatterBlock = createFrontmatterBlock(frontmatterData);
  console.log("✅ Generated frontmatter block:");
  console.log(frontmatterBlock);

  // Test validation
  const isValid = validateFrontmatter(frontmatterData, ["title", "date"]);
  console.log("✅ Validation (title + date required):", isValid);

  const isInvalid = validateFrontmatter(frontmatterData, [
    "title",
    "nonexistent",
  ]);
  console.log("✅ Validation (missing field):", isInvalid, "\n");
};

/**
 * Test blog processing (async)
 */
export const testBlogProcessing = async () => {
  console.log("=== Testing Blog Processing ===");

  try {
    // Test getting all blogs
    const allBlogs = await getAllBlogMeta();
    console.log("✅ Total blogs found:", allBlogs.length);
    console.log(
      "✅ Blog titles:",
      allBlogs.map((b) => b.title)
    );

    // Test getting featured blogs
    const featuredBlogs = await getFeaturedBlogs(2);
    console.log(
      "✅ Featured blogs:",
      featuredBlogs.map((b) => b.title)
    );

    // Test getting specific blog
    const firstBlog = await getBlogBySlug("my-first-trip");
    if (firstBlog) {
      console.log("✅ Specific blog found:", firstBlog.title);
      console.log("✅ Blog has location:", !!firstBlog.location);
      console.log("✅ Blog tags:", firstBlog.tags);
    } else {
      console.log('❌ Blog "my-first-trip" not found');
    }

    // Test blog statistics
    const stats = await getBlogStats();
    console.log("✅ Blog statistics:");
    console.log("   - Total posts:", stats.totalPosts);
    console.log("   - Published posts:", stats.publishedPosts);
    console.log("   - Draft posts:", stats.draftPosts);
    console.log("   - Featured posts:", stats.featuredPosts);
    console.log("   - Posts with location:", stats.postsWithLocation);
    console.log("   - Total tags:", stats.totalTags);
  } catch (error) {
    console.error("❌ Error testing blog processing:", error);
  }

  console.log("\n");
};

/**
 * Run all tests
 */
export const runAllTests = async () => {
  console.log("🚀 Starting Frontmatter System Tests\n");

  testFrontmatterParsing();
  testFrontmatterCreation();
  await testBlogProcessing();

  console.log("✅ All tests completed!\n");
};

// Export for manual testing
export default {
  testFrontmatterParsing,
  testFrontmatterCreation,
  testBlogProcessing,
  runAllTests,
};
